--- #YAML:1.0
name:                Email-MIME-Creator
version:             1.452
abstract:            Email::MIME constructor for starting anew
license:             perl
generated_by:        ExtUtils::MakeMaker version 6.32
distribution_type:   module
requires:     
    Email::MIME:                   1.82
    Email::MIME::Modifier:         1.440
    Email::Simple:                 1.92
    Email::Simple::Creator:        1.4
    Test::More:                    0.47
meta-spec:
    url:     http://module-build.sourceforge.net/META-spec-v1.2.html
    version: 1.2
author:
    - Casey West <casey@geeknest.com>
