# http://module-build.sourceforge.net/META-spec.html
#XXXXXXX This is a prototype!!!  It will change in the future!!! XXXXX#
name:         Email-MIME-Creator
version:      1.2
version_from: lib/Email/MIME/Creator.pm
installdirs:  site
requires:
    Email::MIME:                   1.7
    Email::MIME::Modifier:         
    Email::Simple:                 1.7
    Test::Deep:                    
    Test::More:                    

distribution_type: module
generated_by: ExtUtils::MakeMaker version 6.17
